import type { Metadata } from "next";
import { Inter, Space_Grotesk, Roboto } from "next/font/google";
import "./globals.css";
import LocalFont from "next/font/local";

// const roboto = LocalFont({
//   src: [
//     {
//       path: "./font/Roboto-Regular.woff2",
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "/font/Roboto-Italic.woff2",
//       weight: "400",
//       style: "italic",
//     },
//     {
//       path: "/font/Roboto-Bold.woff2",
//       weight: "700",
//       style: "normal",
//     },
//     {
//       path: "/font/Roboto-BoldItalic.woff2",
//       weight: "700",
//       style: "italic",
//     },
//   ],
// });
const fontHeader = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-header",
  display: "swap",
  adjustFontFallback: false,
  fallback: [
    "DM_Sans",
    "ui-sans-serif",
    "system-ui",
    "-apple-system",
    "BlinkMacSystemFont",
    "Segoe UI",
    "Roboto",
    "Helvetica Neue",
    "Arial",
    "Noto Sans",
    "sans-serif",
    "Apple Color Emoji",
    "Segoe UI Emoji",
    "Noto Color Emoji",
  ],
});
const fontRoboto = {
  fontFamily: "Roboto",
  subsets: ["latin", "latin-ext"], // Example subsets, adjust as needed
  variable: "--font-roboto",
  display: "swap",
  adjustFontFallback: false,
  fallback: [
    "Nunito",
    "ui-sans-serif",
    "system-ui",
    "-apple-system",
    "BlinkMacSystemFont",
    "Segoe UI",
    "Helvetica Neue",
    "Arial",
    "Noto Sans",
    "sans-serif",
    "Apple Color Emoji",
    "Segoe UI Emoji",
    "Noto Color Emoji",
  ],
  weight: "400", // Example weight, adjust as needed
};

export const metadata: Metadata = {
  title: "NELS CARGO & LOGISITCS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontHeader.variable} ${fontRoboto.variable}`}>
        {children}
      </body>
    </html>
  );
}
